version: "3.8"
services:
  mysqldb:
    image: mysql/mysql-server
    env_file: /.env
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=${MYSQLDB_USER:-root}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD:-123456}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      - ${MYSQLDB_DOCKER_PORT}
    volumes:
      - /backend/sql:/docker-entrypoint-initdb.d
    networks:
      - mysqlnet
  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
      #context: /backend
    env_file: /.env
    #restart: on-failure
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - SERVER_PORT=$SPRING_DOCKER_PORT
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&enabledTLSProtocols=TLSv1.2
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD:-123456}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    networks:
      - mysqlnet
    stdin_open: true
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
networks:
  mysqlnet:
    internal: true